### ISSUE TITLE
Database Structure

### ISSUE THREAD

**Issue by robodair** [sudouc/spectrumuc#2]
Define the Firebase structure, write rules in Firebase-Bolt, compile to json rules. Upload to firebase.

Remember the there needs to be a facility for swapping nodes between projects

**Comment by robodair** [comment]
Structure Diagram:
<img width="650" alt="spectrumuc initial database structure" src="https://cloud.githubusercontent.com/assets/8318231/20451807/f8f0c040-ae51-11e6-8e8a-8b57aa48a6c1.png">

**Comment by robodair** [comment]
Structure Diagram:
<img width="686" alt="spectrumuc initial database structure" src="https://cloud.githubusercontent.com/assets/8318231/20451827/4b2be2a4-ae52-11e6-8091-955f7bf72d77.png">

**Comment by sifex** [comment]
This is fine, assuming we can change it when needed. The Pi's should be using this API, and the API is what stays the same, so if they're deployed and we need to alter shit, it should still all be good.

**Comment by robodair** [comment]
Yeah, only the Nodes and Projects trees are of concern to anyone building an app on top. 

Also, It's simple to get a list of nodes associated with a particular project in this structure as well. (order by child 'project' equal to <project uid>)

Obviously not as clean as `/project/nodes/` but means that users can benefit from using the firebase SDK to develop their apps if they want to. (otherwise firebase provides a REST API)

**Comment by sifex** [comment]
You probably can do /project/nodes when doing API calls.
On 19-Nov-16 12:44:15 PM, Alisdair Robertson notifications@github.com wrote:
Yeah, only the Nodes and Projects trees are of concern to anyone building an app on top.
Also, It's simple to get a list of nodes associated with a particular project in this structure as well. (order by child 'project' equal to )
Obviously not as clean as /project/nodes/ but means that users can benefit from using the firebase SDK to develop their apps if they want to. (otherwise firebase provides a REST API)

**Comment by robodair** [comment]
If we add a layer in front of firebase directly then yes, easily. That does mean we would add quite a bit of complexity if we wanted to allow users to use firebase features though.

We could do and document both (a more simple rest API and the more complex but more control firebase API) For now I'm thinking of just documenting the firebase API as it pertains to this project.
